# Generated by Django 4.1 on 2022-09-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='upload')),
                ('sep_text_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TextFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.CharField(max_length=10000)),
                ('sep_text_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('len_text', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
